-- Tables to create in DB
-- user (userID, password, type, balance)
-- books (bookID, title, authors, catID, quantity, price, description, photo)
-- basket (orderID, userID, bookID, quantity, cost, date)
-- category (catID, name)
